# -*- coding: utf-8 -*-
"""Digital Eye.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1A58nJTc-15SBjXyW7aQyE6dJXwHFu11X

**Biblio Setup**
"""

import cv2
from google.colab.patches import cv2_imshow
import numpy as np

"""**Image Loading**"""

image = cv2.imread('evidence.jpg')
print(f"Image shape: {image.shape}")

"""**Resizing**"""

scale_percent = 200
width = int(image.shape[1] * scale_percent / 100)
height = int(image.shape[0] * scale_percent / 100)
resized = cv2.resize(image, (width, height), interpolation=cv2.INTER_LANCZOS4)
resized

"""**Grayscale**"""

gray_image = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)
gray_image

"""**Save**"""

cv2.imwrite('processed_evidence.jpg', gray_image)

"""**Canny Edge Detection**"""

edges = cv2.Canny(gray_image, 100, 200)

print("Original:")
cv2_imshow(image)

print("Edges Only:")
cv2_imshow(edges)
cv2.waitKey(0)