# -*- coding: utf-8 -*-
"""Forensic.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1h4qOWniU_Cc1AaTgOj5-cfuRL20R7Mkv
"""

import cv2
import numpy as np
from google.colab.patches import cv2_imshow

#Load the image
img = cv2.imread('footprint.jpg')
gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)

#Filtering
blurred = cv2.GaussianBlur(gray, (3, 3), 0)

#Edge detection
edges = cv2.Canny(blurred, 200, 150)

#Prespective Warp
src_pts = np.float32([
    [30, 30], [130, 30], [10, 800], [300, 700]
])

#Define the destination
dst_pts = np.float32([[0, 0], [300, 0], [0, 800], [300, 800]])

#Calculate Matrix and Warp
M = cv2.getPerspectiveTransform(src_pts, dst_pts)
flattened = cv2.warpPerspective(img, M, (300, 400))

print("Original Gray with Noise Reduction")
cv2_imshow(blurred)

print("Edge Map")
cv2_imshow(edges)

print("Rectified Evidence")
cv2_imshow(flattened)

gray_flat = cv2.cvtColor(flattened, cv2.COLOR_BGR2GRAY)
blurred_flat = cv2.GaussianBlur(gray_flat, (5, 5), 0)
_, thresh = cv2.threshold(blurred_flat, 0, 255, cv2.THRESH_BINARY_INV + cv2.THRESH_OTSU)
thresh

kernel = np.ones((3,3), np.uint8)
closed_mask = cv2.morphologyEx(thresh, cv2.MORPH_CLOSE, kernel)
closed_mask

contours, _ = cv2.findContours(closed_mask, cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_SIMPLE)

if contours:
  c = max(contours, key=cv2.contourArea)

  x, y, w, h = cv2.boundingRect(c)

  ppcm = 26.6
  actual_length = h / ppcm
  actual_width = w/ ppcm

  result = flattened.copy()
  cv2.rectangle(result, (x, y), (x + w, y + h), (0, 255,0), 2)

  cv2.putText(result, f"L: {h}px", (x +w+5, y+h//2), cv2.FONT_HERSHEY_SIMPLEX, 0.7, (0, 255, 0), 2)
  cv2.putText(result, f"W: {w}px", (x + w//2 - 20, y - 10), cv2.FONT_HERSHEY_SIMPLEX, 0.7, (0, 255, 0), 2)

  print("Measured Footprint (in Pixels):")
  cv2_imshow(result)

  print(f"Foot print Length: {actual_length: .2f}")