# -*- coding: utf-8 -*-
"""Perspective Rectifier.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1V_ZQEFD4ZFJKGhW4Qb6CDtiVUc8_9nPB
"""

import cv2
import numpy as np
from google.colab.patches import cv2_imshow

img = cv2.imread('/content/crime_scene.jpg')
rows, cols, ch = img.shape
print(rows, cols, ch)

#Define 4 corner points of the tape
pts1 = np.float32([[100,100], [450,50], [100, 400], [400, 350]])

#Landing points
pts2 = np.float32([[0,0], [600,0], [0,200], [400,200]])

#Transformation Matrix
M = cv2.getPerspectiveTransform(pts1, pts2)

#Apply
dst = cv2.warpPerspective(img, M, (500,200))

cv2_imshow(dst)

hsv = cv2.cvtColor(dst, cv2.COLOR_BGR2HSV)

#Define the range of "Red" in HSV
lower_yllow = np.array([20, 100, 100])
upper_yllow = np.array([30, 255, 255])

#Mask Creation
mask = cv2.inRange(hsv, lower_yllow, upper_yllow)

#Showing the original color through the mask
result = cv2.bitwise_and(dst, dst, mask=mask)

cv2_imshow(result)
cv2.waitKey(0)