# -*- coding: utf-8 -*-
"""The Evidence Highlighter.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1FE8w1BYJ1fLN759ZAKsFzv3Yi4mRjdtb
"""

import cv2
from google.colab.patches import cv2_imshow
import numpy as np

def find_evidence(image_path):
  img = cv2.imread(image_path)

  #Convert BGR to HSV
  hsv = cv2.cvtColor(img, cv2.COLOR_BGR2HSV)

  #Define the range of "Red" in HSV
  lower_red = np.array([0, 120, 70])
  upper_red = np.array([10, 255, 255])

  #Mask Creation
  mask = cv2.inRange(hsv, lower_red, upper_red)

  #Showing the original color through the mask
  result = cv2.bitwise_and(img, img, mask=mask)

  print("Evidence Found")
  cv2_imshow(result)
  cv2.waitKey(0)

find_evidence('/content/images.jpg')

def find_evidence(image_path):
  img = cv2.imread(image_path)

  #Convert BGR to HSV
  hsv = cv2.cvtColor(img, cv2.COLOR_BGR2HSV)

  #Define the range of "Yallow" in HSV
  lower_red = np.array([20, 100, 100])
  upper_red = np.array([30, 255, 255])

  #Mask Creation
  mask = cv2.inRange(hsv, lower_red, upper_red)

  #Clean up the mask
  mask = cv2.erode(mask, None, iterations=2)
  mask = cv2.dilate(mask, None, iterations=2)

  #Showing the original color through the mask
  result = cv2.bitwise_and(img, img, mask=mask)

  print("Evidence Found")
  cv2_imshow(result)
  cv2.waitKey(0)

find_evidence('/content/crime_scene.jpg')